[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/*.fbx"
  [headers.values]
    Content-Type = "application/octet-stream"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/*.glb"
  [headers.values]
    Content-Type = "model/gltf-binary"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/*.gltf"
  [headers.values]
    Content-Type = "model/gltf+json"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/models/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
